### ISSUE TITLE
Count isn't shown for the zeros

### ISSUE THREAD

**Issue by ranjjose-chaz** [AnushaChengi/H.Tasks#2]

**Comment by AnushaChengi** [comment]
#include <stdio.h>
int main()
{
    int n, i, j, count=0, a[100];
    printf("Enter the number of elements in array\n");
    scanf("%d", &n);
    printf("Enter the elements of the array");
    for(i=0;i<n;i++)
    {
        scanf("%d",&a[i]);
    }
    for(i=0;i<n;i++)
    {
        count = 0;
        for (j=0;j<n;j++)
        {
            if(j<i && a[i]==a[j])
                break;
        else if(a[i]==a[j])
        {
                count++;
        }
        }
        if(count>0)
        {
            printf("%d occurs %d times\n",a[i],count);
        }
    }
}

//output
Enter the number of elements in array
6
Enter the elements of the array
0
0
0
2
2
3
0 occurs 3 times
2 occurs 2 times
3 occurs 1 times
Program ended with exit code: 0
